# 生产环境配置
example:
    knife4j: # 关闭knife4j
        production: true
    mysql:
        host: example-mysql
        password: ${MYSQL_PASSWORD:-123456}
    redis:
        host: example-redis
        password: ${REDIS_PASSWORD:-123456}
    rabbitmq:
        host: example-rabbitmq
        password: ${RABBITMQ_PASSWORD:-123456}
